### ISSUE TITLE
Compatibility issue in Windows 7

### ISSUE THREAD

**Issue by skojaku** [skojaku/km_config#1]
An error is raised when compiling c++ package under Windows 7 with cygwins.

**Comment by QingzhouL** [comment]
Now,the code can be compiled under Windows7 with cygwin64. However, the options parameters of km_config command don't seem to work. I use the km_config command as the following three sentences, but the outputs of the three sentences in the command window are the same (for example, The Number of runs are always 10 even if I set the R times=15 (-r 15).

Three different sentence:
$ ./km_config example_edge_list.txt result.txt
$ ./km_config example_edge_list.txt result2.txt -r 15
$ ./km_config example_edge_list.txt result.txt -a 0.05 


The outputs in the command window are always same as following:
===================
# input file:  example_edge_list.txt
# output file: result.txt

# Status:
   Reading input file...
   Number of nodes: 20
   Number of edges: 140

   Seeking core-periphery pairs...
      - Number of runs: 10
   end


# Results:
   Number of significant core-periphery pairs: 2
   Number of insignificant core-periphery pairs: 0
   Save to result.txt...
   end
===================

**Comment by QingzhouL** [comment]
Now,the code can be compiled under Windows with cygwin64. However, the options parameters of km_config command don't seem to work.
I use the km_config command as the following three sentences, but the outputs of the three sentence in the command window are the same,
(for example, The Number of runs are always 10 even if I set the R times=15 (-r 15).

Three different sentence:
$ ./km_config example_edge_list.txt result.txt
$ ./km_config example_edge_list.txt result2.txt -r 15
$ ./km_config example_edge_list.txt result.txt -a 0.05 


The outputs in the command window are always same as following:
===================
# input file:  example_edge_list.txt
# output file: result.txt

# Status:
   Reading input file...
   Number of nodes: 20
   Number of edges: 140

   Seeking core-periphery pairs...
      - Number of runs: 10
   end


# Results:
   Number of significant core-periphery pairs: 2
   Number of insignificant core-periphery pairs: 0
   Save to result.txt...
   end
===================

**Comment by QingzhouL** [comment]
Now,the code can be compiled under Windows with cygwin64. However, the options parameters of km_config command don't seem to work.
I use the km_config command as the following three sentences, but the outputs of the three sentence in the command window are the same,
(for example, The Number of runs are always 10 even if I set the R times=15 (-r 15).

Three different sentence:
$ ./km_config example_edge_list.txt result.txt
$ ./km_config example_edge_list.txt result2.txt -r 15
$ ./km_config example_edge_list.txt result.txt -a 0.05 


The outputs in the command window are always same as following:
===================
input file:  example_edge_list.txt
output file: result.txt

Status:
   Reading input file...
   Number of nodes: 20
   Number of edges: 140

   Seeking core-periphery pairs...
      - Number of runs: 10
   end


Results:
   Number of significant core-periphery pairs: 2
   Number of insignificant core-periphery pairs: 0
   Save to result.txt...
   end
===================

**Comment by skojaku** [comment]
Alright. The problem is due to <getopt.h> library that works under Linux but not in Windows. I am working on making it work under Windows. Thanks for raising the issue.

**Comment by skojaku** [comment]
I have amended the code to be compatible with VisualStudio. Please do either of the following, recompile and try it again.
 
- Under the root directory (where you can see README.txt), type 
`git pull && git checkout fix-windows-compatibility
`
- If you are not sure how to git-pull, download the package
https://github.com/skojaku/km_config/archive/fix-windows-compatibility.zip

**Comment by QingzhouL** [comment]
Now The code(fix-windows-compatibility.zip) works well. Thank you very much, Skojaku.
